BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[AcceptedOrders] ADD [secfreight] FLOAT(53) NOT NULL CONSTRAINT [AcceptedOrders_secfreight_df] DEFAULT 0,
[vehno] NVARCHAR(1000) NOT NULL CONSTRAINT [AcceptedOrders_vehno_df] DEFAULT '';

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
