BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[admin] (
    [admin_id] NVARCHAR(1000) NOT NULL,
    [username] NVARCHAR(1000) NOT NULL,
    [password] NVARCHAR(1000) NOT NULL,
    CONSTRAINT [admin_pkey] PRIMARY KEY CLUSTERED ([admin_id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
