BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[partyImages] ADD [userId] INT;

-- AddForeignKey
ALTER TABLE [dbo].[partyImages] ADD CONSTRAINT [partyImages_userId_fkey] FOREIGN KEY ([userId]) REFERENCES [dbo].[User]([user_id]) ON DELETE SET NULL ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
