BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Order] ADD [status] NVARCHAR(1000) NOT NULL CONSTRAINT [Order_status_df] DEFAULT 'pending';

-- AlterTable
ALTER TABLE [dbo].[User] ADD [stcd] NVARCHAR(1000) NOT NULL CONSTRAINT [User_stcd_df] DEFAULT '',
[stnm] NVARCHAR(1000) NOT NULL CONSTRAINT [User_stnm_df] DEFAULT '',
[untnm] NVARCHAR(1000) NOT NULL CONSTRAINT [User_untnm_df] DEFAULT '';

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
